---
title: "Spatial Access -- DOC"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      collapse = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      comment = "#>",
                      fig.path = "markdown/doc/")
library(here)
source(here("code/0-packages.R"))
theme_set(theme_bw())
```

```{r}
doc = read.csv(here("data/processed/doc.csv"))  %>% 
  mutate(Amendments = factor(Amendments, levels = c("control", "C", "N")),
         Homogenization = factor(Homogenization, levels = c("Intact", "Homogenized")))

```

```{r doc_graph, fig.width=8}
doc %>% 
  ggplot(aes(x = Amendments, y = DOC_mg_L, color = Amendments))+
  geom_point()+
  facet_grid(Suction~Homogenization+Moisture+Wetting, scales = "free_y")+
  theme(legend.position = "none")

doc %>% 
  ggplot(aes(x = Amendments, y = DOC_mg, color = Amendments))+
  geom_point()+
  facet_grid(Suction~Homogenization+Moisture+Wetting, scales = "free_y")+
  theme(legend.position = "none")
```

---

how much DOC was added as part of the amendment?

5 mL of 10.1 M acetate (CH3-COO-K)  
1 mole acetate = 2 mole C

10.1 M acetate = 20.2 M C = (20.2 * 12) g/L C  
5 mL of 10.1 M acetate = 0.005 L * 20.2 * 12 g/L C = `r 0.005 * 20.2 * 12` g C

---
#### Session Info

<details>
  <summary>click to expand</summary>
  
  
Date run: `r Sys.Date()`

```{r}
sessionInfo()
```

</details>
