---
title: "Spatial Access -- Results"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      collapse = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      comment = "#>",
                      fig.path = ("markdown/results/"))
```

```{r load}
library(here)
source(here("code/0-packages.R"))
library(gt)
library(lme4)
library(multcomp)



theme_set(theme_bw())
pal = pnw_palette("Bay", 3)

```


# FTICR
```{r files}
# data_long = read.csv(here("data/processed/fticr_long_core.csv.gz"))
# data = read.csv(here("data/processed/fticr_long_key.csv.gz")) %>% 
#    #filter(n>2) %>% 
#    mutate(Homogenization = factor(Homogenization, levels = c("Intact", "Homogenized")),
#          Amendments = factor(Amendments, levels = c("control", "C", "N"))) %>% 
#    filter(!Suction==15)
# data_long_trt = read.csv(here("data/processed/fticr_long_trt.csv.gz"))

meta = read.csv(here("data/processed/fticr_meta.csv"))
meta_hcoc = 
  meta %>% 
  dplyr::select(formula, HC, OC)
```

```{r load_files}
fticr_key = read.csv(here("data/processed/fticr_key.csv")) %>% 
   distinct(SampleAssignment, Moisture, Wetting, Amendments, Suction, Homogenization)

fticr_data_key = read.csv(here("data/processed/fticr_long_key.csv.gz")) %>% 
     mutate(Homogenization = factor(Homogenization, levels = c("Intact", "Homogenized")),
            Amendments = factor(Amendments, levels = c("control", "C", "N")),
            Moisture = factor(Moisture, levels = c("fm", "drought")),
            Wetting = factor(Wetting, levels = c("precip", "groundw"))) 

meta_classes = 
  meta %>% 
  dplyr::select(formula, class)
```

```{r fticr_peaks}
peaks_distinct = 
   fticr_data_key %>% 
   group_by(SampleAssignment) %>% 
   distinct(formula)

peakcounts = 
   peaks_distinct %>% 
   left_join(meta_classes, by = "formula") %>% 
  group_by(SampleAssignment, class) %>% 
  summarize(n = n()) %>% 
  ungroup() %>% 
  group_by(SampleAssignment) %>% 
  dplyr::mutate(total = sum(n)) %>% 
  spread(class, n) %>% 
  pivot_longer(-c(SampleAssignment),
               names_to = "class") %>% 
  ungroup() %>% 
  group_by(SampleAssignment, class) %>% 
   dplyr::summarize(peaks = as.integer(mean(value))) %>% 
  #spread(name, peaks) %>% 
   left_join(fticr_key, by = "SampleAssignment") %>% 
   ungroup %>% 
  dplyr::select(-SampleAssignment) %>% 
   mutate(Amendments = factor(Amendments, 
                              levels = c("control", "C", "N")),
          class = factor(class, levels = 
                          c("aliphatic", "aliphatic+N","unsaturated","aromatic","condensed_arom", "other", "total")))
```


## Aromatic Peaks

```{r table_aromatic_peak_counts1, eval=FALSE}
peakcounts %>% 
   filter(class %in% c("aromatic", "condensed_arom") & !Suction == 15 & Homogenization=="Intact") %>%
   group_by(Suction, Moisture, Wetting, Amendments, Homogenization) %>% 
   summarise(peaks=sum(peaks)) %>% 
   ungroup() %>% 
   #select(-class) %>% 
   mutate(var = paste0(Suction,"-",Amendments),
          var = factor(var, levels = c("1.5-control", "1.5-C", "1.5-N",
                                       "50-control", "50-C", "50-N")),
          Homogenization = factor(Homogenization, levels = c("Intact", "Homogenized"))) %>% 
   dplyr::select(-Suction,-Amendments) %>% 
   spread(var, peaks) %>% 
   gt(rowname_col = "row", groupname_col = "Homogenization") %>% 
   tab_spanner(label = "1.5 kPa", columns = contains("1.5")) %>% 
   tab_spanner(label = "50 kPa", columns = contains("50")) %>% 
   tab_header(
    title = md("Distinct Aromatic Peaks Present")
  )
```

```{r peaks_aromatic}
aromatic_counts_by_core = 
  fticr_data_key %>% 
  filter(!Suction == 15) %>%
  left_join(meta_classes, by = "formula") %>% 
  filter(class %in% c("aromatic", "condensed_arom")) %>% 
  group_by(Core, Suction, Moisture, Wetting, Amendments, Homogenization) %>% 
  summarise(arom_peaks=sum(presence)) %>% 
  ungroup() 

aromatic_counts_by_core_intact = 
  aromatic_counts_by_core %>% 
  filter(Homogenization=="Intact")

aromatic_counts_by_core_homo = 
  aromatic_counts_by_core %>% 
  filter(Homogenization=="Homogenized")
```

```{r peaks_arom_ggplot, fig.width=7, fig.height=4}
arom_label = tribble(
  ~Suction, ~Amendments, ~arom_peaks, ~label,
  1.5, "control", 400, "b",
  1.5, "C", 600, "a",
  1.5, "N", 400, "ab",
  50, "control", 650, "b",
  50, "C", 900, "a",
  50, "N", 450, "b"
  ) %>% 
  mutate(Wetting="precip", Moisture="fm")

aromatic_counts_by_core_intact %>% 
  ggplot(aes(x = Amendments, y = arom_peaks, color = Moisture, shape = interaction(Moisture, Wetting)))+
  geom_boxplot(fill=NA, color = "grey", aes(group=Amendments))+
  geom_point(size=3, stroke=1, position = position_dodge(width = 0.7))+
  scale_shape_manual(values = c(1,2,19,17))+
  
  facet_grid(.~Suction)+
  labs(title = "aromatic peaks in intact cores",
       subtitle = "AImod > 0.5",
       shape = "")+
  geom_text(data = arom_label, aes(label = label), color = "black")+
#  theme(panel.grid = element_blank())+
  NULL

aromatic_counts_by_core_intact %>% 
  ggplot(aes(x = Suction, y = arom_peaks, shape = Wetting))+
  geom_point(position = position_dodge(width = 5))


```

<details>
  <summary>Statistics - click to open</summary>

Overall lmer (REML)

```{r peaks_arom_stats_lmer}
car::Anova(lmer(
  arom_peaks ~ (Homogenization + Moisture + Wetting + Amendments + Suction)^2 + (1|Core),
  REML = TRUE,
  data = aromatic_counts_by_core
))
```

Intact cores ANOVA

```{r peaks_arom_stats_aov_intact}
print("intact cores: aov(arom_peaks ~ (Moisture + Wetting + Amendments + Suction)")
arom_aov_int = aov(arom_peaks ~ (Moisture * Wetting * Amendments * Suction), 
                   data = aromatic_counts_by_core_intact)
summary(arom_aov_int)

h = agricolae::HSD.test(arom_aov_int, trt = "Amendments"); h$groups

interaction.plot(aromatic_counts_by_core_intact$Suction,
                 aromatic_counts_by_core_intact$Wetting,
                 aromatic_counts_by_core_intact$arom_peaks)


```

Homogenized cores ANOVA

```{r peaks_arom_stats_aov_homo}
print("homogenized cores: aov(arom_peaks ~ (Moisture + Wetting + Amendments + Suction)")
arom_aov_homo = aov(arom_peaks ~ (Moisture + Wetting + Amendments + Suction)^2, 
                   data = aromatic_counts_by_core_homo)
summary(arom_aov_homo)

h = agricolae::HSD.test(arom_aov_homo, trt = "Amendments"); h$groups
## C = a, control = a, N = b 
```

</details>

```{r peaks_summary table}
aromatic_summary_moisture = 
  aromatic_counts_by_core_intact %>% 
  group_by(Moisture) %>% 
  dplyr::summarise(arom = mean(arom_peaks),
                   se = sd(arom_peaks)/sqrt(n())) %>% 
  mutate(arom_peaks = paste(as.integer(arom), "\u00b1", as.integer(se)),
         treatment = "Moisture*") %>% 
  rename(level = Moisture) %>% 
  dplyr::select(treatment, level, arom_peaks)

aromatic_summary_wetting = 
  aromatic_counts_by_core_intact %>% 
  group_by(Wetting) %>% 
  dplyr::summarise(arom = mean(arom_peaks),
                   se = sd(arom_peaks)/sqrt(n())) %>% 
  mutate(arom_peaks = paste(as.integer(arom), "\u00b1", as.integer(se)),
         treatment = "Wetting*") %>% 
  rename(level = Wetting) %>% 
  dplyr::select(treatment, level, arom_peaks)

aromatic_summary_amend = 
  aromatic_counts_by_core_intact %>% 
  group_by(Amendments) %>% 
  dplyr::summarise(arom = mean(arom_peaks),
                   se = sd(arom_peaks)/sqrt(n())) %>% 
  mutate(arom_peaks = paste(as.integer(arom), "\u00b1", as.integer(se)),
         treatment = "Amendments*") %>%
  rename(level = Amendments) %>% 
  dplyr::select(treatment, level, arom_peaks)

aromatic_summary_suction = 
  aromatic_counts_by_core_intact %>% 
  group_by(Suction) %>% 
  dplyr::summarise(arom = mean(arom_peaks),
                   se = sd(arom_peaks)/sqrt(n())) %>% 
  mutate(arom_peaks = paste(as.integer(arom), "\u00b1", as.integer(se)),
         treatment = "Suction*",
         Suction = as.character(Suction)) %>%
  rename(level = Suction) %>% 
  dplyr::select(treatment, level, arom_peaks)

aromatic_summary_homo = 
  aromatic_counts_by_core %>% 
  group_by(Homogenization) %>% 
  dplyr::summarise(arom = mean(arom_peaks),
                   se = sd(arom_peaks)/sqrt(n())) %>% 
  mutate(arom_peaks = paste(as.integer(arom), "\u00b1", as.integer(se)),
         treatment = "Homogenization") %>%
  rename(level = Homogenization) %>% 
  dplyr::select(treatment, level, arom_peaks)

aromatic_summary_all = 
  rbind(aromatic_summary_moisture,
        aromatic_summary_wetting,
        aromatic_summary_amend,
        aromatic_summary_suction,
        aromatic_summary_homo)

```

## Total Peaks

```{r peaks_total}
total_counts_by_core = 
  fticr_data_key %>% 
  filter(!Suction == 15) %>%
#  left_join(meta_classes, by = "formula") %>% 
#  filter(class %in% "total") %>% 
  group_by(Core, Suction, Moisture, Wetting, Amendments, Homogenization) %>% 
  summarise(total_peaks=sum(presence)) %>% 
  ungroup() 

total_counts_by_core_intact = 
  total_counts_by_core %>% 
  filter(Homogenization=="Intact")

total_counts_by_core_homo = 
  total_counts_by_core %>% 
  filter(Homogenization=="Homogenized")
```

```{r peaks_total_ggplot, eval=FALSE}
total_counts_by_core_intact %>% 
  ggplot( aes(x = Amendments, y = total_peaks, color = Moisture, shape = Wetting))+
  geom_boxplot(fill=NA, color = "grey", aes(group=Amendments))+
  geom_point(size=2, position = position_dodge(width = 0.7))+
  facet_grid(.~Suction)+
  labs(title = "total peaks in intact cores")+
  #geom_text(data = arom_label, aes(label = label), color = "black")+
#  theme(panel.grid = element_blank())+
  NULL
```

<details>
  <summary>Statistics - click to expand</summary>
  
Overall lmer (REML) 
```{r peaks_total_stats_lmer}
car::Anova(lmer(
  total_peaks ~ (Homogenization + Moisture + Wetting + Amendments + Suction)^2 + (1|Core),
  REML = TRUE,
  data = total_counts_by_core
))
```

Intact cores

```{r peaks_total_stats_aov_intact}
print("intact cores: aov(arom_peaks ~ (Moisture + Wetting + Amendments + Suction)")
total_aov_int = aov(total_peaks ~ (Moisture + Wetting + Amendments + Suction)^2, 
                   data = total_counts_by_core_intact)
summary(total_aov_int)

h = agricolae::HSD.test(arom_aov_int, trt = "Amendments"); h$groups
## C=a, N=b, control=b
```

Homogenized cores

```{r peaks_total_stats_aov_homo}
print("homogenized cores: aov(arom_peaks ~ (Moisture + Wetting + Amendments + Suction)")
total_aov_homo = aov(total_peaks ~ (Moisture + Wetting + Amendments + Suction)^2, 
                   data = total_counts_by_core_homo)
summary(total_aov_homo)

h = agricolae::HSD.test(total_aov_homo, trt = "Amendments"); h$groups
## C=a, control=a, N=b 
```

</details>

```{r peaks_total_summary_table}
total_summary_moisture = 
  total_counts_by_core_intact %>% 
  group_by(Moisture) %>% 
  dplyr::summarise(total = mean(total_peaks),
                   se = sd(total_peaks)/sqrt(n())) %>% 
  mutate(total_peaks = paste(as.integer(total), "\u00b1", as.integer(se)),
         treatment = "Moisture*") %>% 
  rename(level = Moisture) %>% 
  dplyr::select(treatment, level, total_peaks)

total_summary_wetting = 
  total_counts_by_core_intact %>% 
  group_by(Wetting) %>% 
  dplyr::summarise(total = mean(total_peaks),
                   se = sd(total_peaks)/sqrt(n())) %>% 
  mutate(total_peaks = paste(as.integer(total), "\u00b1", as.integer(se)),
         treatment = "Wetting*") %>% 
  rename(level = Wetting) %>% 
  dplyr::select(treatment, level, total_peaks)

total_summary_amend = 
  total_counts_by_core_intact %>% 
  group_by(Amendments) %>% 
  dplyr::summarise(total = mean(total_peaks),
                   se = sd(total_peaks)/sqrt(n())) %>% 
  mutate(total_peaks = paste(as.integer(total), "\u00b1", as.integer(se)),
         treatment = "Amendments*") %>%
  rename(level = Amendments) %>% 
  dplyr::select(treatment, level, total_peaks)

total_summary_suction = 
  total_counts_by_core_intact %>% 
  group_by(Suction) %>% 
  dplyr::summarise(total = mean(total_peaks),
                   se = sd(total_peaks)/sqrt(n())) %>% 
  mutate(total_peaks = paste(as.integer(total), "\u00b1", as.integer(se)),
         treatment = "Suction*",
         Suction = as.character(Suction)) %>%
  rename(level = Suction) %>% 
  dplyr::select(treatment, level, total_peaks)

total_summary_homo = 
  total_counts_by_core %>% 
  group_by(Homogenization) %>% 
  dplyr::summarise(total = mean(total_peaks),
                   se = sd(total_peaks)/sqrt(n())) %>% 
  mutate(total_peaks = paste(as.integer(total), "\u00b1", as.integer(se)),
         treatment = "Homogenization") %>%
  rename(level = Homogenization) %>% 
  dplyr::select(treatment, level, total_peaks)

total_summary_all = 
  rbind(total_summary_moisture,
        total_summary_wetting,
        total_summary_amend,
        total_summary_suction,
        total_summary_homo)
```

## FTICR summary tables
```{r}
left_join(total_summary_all, aromatic_summary_all) %>% 
  knitr::kable()
```


---

<details>
  <summary>Session Info</summary>
  
Date: `r Sys.Date()`

```{r}
sessionInfo()
```

